<% jdbc = defined?(JRUBY_VERSION) ? 'jdbc' : '' %>  #' Fix vim highlighting

production:
  adapter: <%= jdbc %>mysql2
  database: db
  pool: 35
  username: root
  password: kathmandu09
  host: localhost
  encoding: utf8

development:
  adapter: <%= jdbc %>mysql2
  database: db
  pool: 35
  username: root
  password: kathmandu09
  host: localhost
  encoding: utf8