production:
  adapter: postgresql
  host: localhost
  username: postgres
  password:
  database: db
  encoding: UTF8

development:
  adapter: postgresql
  host: localhost
  username: postgres
  password:
  database: db
  encoding: UTF8